-- ==============================================================================
-- KOVAION ENTERPRISE SUITE - FINANCE & OPERATIONS
-- PHASE 4: VIEWS AND PL/SQL BUSINESS LOGIC (FINAL CORRECTED)
-- ==============================================================================

-- ==========================================
-- 1. VIEWS
-- ==========================================

-- 1.1 INVOICE SUMMARY
CREATE OR REPLACE VIEW KF_VW_INVOICE_SUMMARY AS
SELECT 
    i.INVOICE_ID,
    i.INVOICE_NUMBER,
    i.VENDOR_ID,
    v.VENDOR_NAME,
    i.FISCAL_YEAR_ID,
    f.FISCAL_YEAR_CODE,
    i.INVOICE_DATE,
    i.DUE_DATE,
    i.CURRENCY AS CURRENCY_CODE,
    i.SUBTOTAL,
    i.TAX_AMOUNT,
    i.TDS_AMOUNT,
    i.TOTAL_AMOUNT,
    i.STATUS,
    i.SOURCE_TYPE AS SOURCE,
    i.CREATED_DATE AS CREATED_AT,
    i.UPDATED_DATE AS UPDATED_AT
FROM KF_INVOICES i
JOIN KF_VENDORS v ON i.VENDOR_ID = v.VENDOR_ID
LEFT JOIN KF_FISCAL_YEARS f ON i.FISCAL_YEAR_ID = f.FISCAL_YEAR_ID;

-- 1.2 INVOICE BALANCES
CREATE OR REPLACE VIEW KF_VW_INVOICE_BALANCES AS
SELECT 
    i.INVOICE_ID,
    i.INVOICE_NUMBER,
    v.VENDOR_NAME,
    i.TOTAL_AMOUNT,
    NVL(p.TOTAL_PAID, 0) AS TOTAL_PAID,
    (i.TOTAL_AMOUNT - NVL(p.TOTAL_PAID, 0)) AS BALANCE_AMOUNT,
    CASE 
        WHEN i.STATUS IN ('DRAFT', 'REJECTED', 'CANCELLED', 'PENDING_APPROVAL', 'OVERDUE') THEN i.STATUS
        WHEN NVL(p.TOTAL_PAID, 0) = 0 THEN 'UNPAID'
        WHEN NVL(p.TOTAL_PAID, 0) > 0 AND NVL(p.TOTAL_PAID, 0) < i.TOTAL_AMOUNT THEN 'PARTIALLY_PAID'
        WHEN NVL(p.TOTAL_PAID, 0) >= i.TOTAL_AMOUNT THEN 'PAID'
    END AS PAYMENT_STATUS
FROM KF_INVOICES i
JOIN KF_VENDORS v ON i.VENDOR_ID = v.VENDOR_ID
LEFT JOIN (
    SELECT INVOICE_ID, SUM(PAYMENT_AMOUNT) AS TOTAL_PAID
    FROM KF_PAYMENTS
    WHERE STATUS = 'COMPLETED'
    GROUP BY INVOICE_ID
) p ON i.INVOICE_ID = p.INVOICE_ID;

-- 1.3 PAYMENT SUMMARY
CREATE OR REPLACE VIEW KF_VW_PAYMENT_SUMMARY AS
SELECT 
    p.PAYMENT_ID,
    p.INVOICE_ID,
    i.INVOICE_NUMBER,
    p.VENDOR_ID,
    v.VENDOR_NAME,
    p.PAYMENT_DATE,
    p.PAYMENT_AMOUNT,
    p.PAYMENT_METHOD,
    p.REFERENCE_NUMBER,
    p.STATUS,
    p.CREATED_DATE AS CREATED_AT
FROM KF_PAYMENTS p
JOIN KF_INVOICES i ON p.INVOICE_ID = i.INVOICE_ID
JOIN KF_VENDORS v ON p.VENDOR_ID = v.VENDOR_ID;

-- 1.4 PENDING APPROVALS
CREATE OR REPLACE VIEW KF_VW_PENDING_APPROVALS AS
SELECT 
    a.APPROVAL_ID AS APPROVAL_REQUEST_ID,
    a.ENTITY_TYPE,
    a.ENTITY_ID,
    a.REQUESTED_BY,
    a.REQUESTED_DATE AS REQUESTED_AT,
    a.STATUS,
    a.ASSIGNED_APPROVER,
    a.DECISION_DATE,
    a.COMMENTS
FROM KF_APPROVAL_REQUESTS a
WHERE a.STATUS = 'PENDING';

-- 1.5 CASH FLOW MONTHLY
CREATE OR REPLACE VIEW KF_VW_CASH_FLOW_MONTHLY AS
SELECT 
    t.FISCAL_YEAR_ID,
    TO_CHAR(e.TRANSACTION_DATE, 'YYYY') AS YEAR,
    TO_CHAR(e.TRANSACTION_DATE, 'MM') AS MONTH,
    TO_CHAR(e.TRANSACTION_DATE, 'Mon') AS MONTH_NAME,
    SUM(CASE WHEN e.TRANSACTION_TYPE = 'INFLOW' THEN e.AMOUNT ELSE 0 END) AS INFLOW,
    SUM(CASE WHEN e.TRANSACTION_TYPE = 'OUTFLOW' THEN e.AMOUNT ELSE 0 END) AS OUTFLOW,
    SUM(CASE WHEN e.TRANSACTION_TYPE = 'INFLOW' THEN e.AMOUNT ELSE 0 END) - 
    SUM(CASE WHEN e.TRANSACTION_TYPE = 'OUTFLOW' THEN e.AMOUNT ELSE 0 END) AS NET_CASH_FLOW
FROM KF_CASH_FLOW_ENTRIES e
JOIN KF_CASH_FLOW_TRACKERS t ON e.TRACKER_ID = t.TRACKER_ID
WHERE e.STATUS = 'ACTIVE' AND t.STATUS = 'APPROVED'
GROUP BY t.FISCAL_YEAR_ID, TO_CHAR(e.TRANSACTION_DATE, 'YYYY'), TO_CHAR(e.TRANSACTION_DATE, 'MM'), TO_CHAR(e.TRANSACTION_DATE, 'Mon');

-- 1.6 TDS SUMMARY
CREATE OR REPLACE VIEW KF_VW_TDS_SUMMARY AS
SELECT 
    t.TDS_SECTION,
    SUM(t.TAXABLE_AMOUNT) AS TOTAL_TAXABLE_AMOUNT,
    SUM(t.TDS_AMOUNT) AS TOTAL_TDS,
    SUM(CASE WHEN t.STATUS = 'PENDING' THEN t.TDS_AMOUNT ELSE 0 END) AS PENDING_TDS,
    SUM(CASE WHEN t.STATUS = 'DEPOSITED' THEN t.TDS_AMOUNT ELSE 0 END) AS DEPOSITED_TDS
FROM KF_TDS_TRANSACTIONS t
GROUP BY t.TDS_SECTION;

-- 1.7 VENDOR SUMMARY
CREATE OR REPLACE VIEW KF_VW_VENDOR_SUMMARY AS
SELECT 
    v.VENDOR_ID,
    v.VENDOR_CODE,
    v.VENDOR_NAME,
    COUNT(i.INVOICE_ID) AS TOTAL_INVOICES,
    NVL(SUM(i.TOTAL_AMOUNT), 0) AS TOTAL_INVOICE_VALUE,
    NVL(SUM(b.TOTAL_PAID), 0) AS TOTAL_PAID,
    NVL(SUM(b.BALANCE_AMOUNT), 0) AS OUTSTANDING_AMOUNT,
    NVL(SUM(CASE WHEN i.DUE_DATE < SYSDATE AND b.BALANCE_AMOUNT > 0 THEN b.BALANCE_AMOUNT ELSE 0 END), 0) AS OVERDUE_AMOUNT
FROM KF_VENDORS v
LEFT JOIN KF_INVOICES i ON v.VENDOR_ID = i.VENDOR_ID AND i.STATUS != 'CANCELLED'
LEFT JOIN KF_VW_INVOICE_BALANCES b ON i.INVOICE_ID = b.INVOICE_ID
GROUP BY v.VENDOR_ID, v.VENDOR_CODE, v.VENDOR_NAME;

-- 1.8 DASHBOARD KPIS
CREATE OR REPLACE VIEW KF_VW_DASHBOARD_KPIS AS
SELECT
    (SELECT COUNT(*) FROM KF_INVOICES WHERE STATUS != 'CANCELLED') AS TOTAL_INVOICES,
    (SELECT COUNT(*) FROM KF_APPROVAL_REQUESTS WHERE STATUS = 'PENDING') AS PENDING_APPROVALS,
    (SELECT NVL(SUM(TOTAL_AMOUNT), 0) FROM KF_INVOICES WHERE STATUS != 'CANCELLED') AS TOTAL_INVOICE_VALUE,
    (SELECT NVL(SUM(PAYMENT_AMOUNT), 0) FROM KF_PAYMENTS WHERE STATUS = 'COMPLETED') AS TOTAL_PAID,
    (SELECT NVL(SUM(BALANCE_AMOUNT), 0) FROM KF_VW_INVOICE_BALANCES WHERE PAYMENT_STATUS IN ('UNPAID', 'PARTIALLY_PAID', 'OVERDUE')) AS TOTAL_OUTSTANDING,
    (SELECT COUNT(*) FROM KF_VENDORS WHERE STATUS = 'ACTIVE') AS TOTAL_VENDORS,
    (SELECT NVL(SUM(TDS_AMOUNT), 0) FROM KF_TDS_TRANSACTIONS WHERE STATUS = 'PENDING') AS TOTAL_TDS
FROM DUAL;


-- ==========================================
-- 2. PACKAGE SPECIFICATIONS
-- ==========================================

CREATE OR REPLACE PACKAGE KF_PKG_AUDIT AS
    PROCEDURE LOG_EVENT (
        P_USER_ID IN NUMBER,
        P_ACTION IN VARCHAR2,
        P_TABLE_NAME IN VARCHAR2,
        P_RECORD_ID IN VARCHAR2,
        P_OLD_VALUE IN CLOB DEFAULT NULL,
        P_NEW_VALUE IN CLOB DEFAULT NULL
    );
END KF_PKG_AUDIT;
/

CREATE OR REPLACE PACKAGE KF_PKG_NOTIFICATION AS
    PROCEDURE CREATE_NOTIFICATION (
        P_USER_ID IN NUMBER,
        P_TITLE IN VARCHAR2,
        P_MESSAGE IN VARCHAR2,
        P_TYPE IN VARCHAR2 DEFAULT 'INFO',
        P_RELATED_ENTITY_TYPE IN VARCHAR2 DEFAULT NULL,
        P_RELATED_ENTITY_ID IN NUMBER DEFAULT NULL
    );
    PROCEDURE MARK_AS_READ (P_NOTIFICATION_ID IN NUMBER);
    PROCEDURE MARK_ALL_AS_READ (P_USER_ID IN NUMBER);
END KF_PKG_NOTIFICATION;
/

CREATE OR REPLACE PACKAGE KF_PKG_FISCAL_YEAR AS
    FUNCTION GET_CURRENT_FISCAL_YEAR RETURN NUMBER;
    FUNCTION IS_DATE_IN_FISCAL_YEAR (P_DATE IN DATE, P_FISCAL_YEAR_ID IN NUMBER) RETURN BOOLEAN;
END KF_PKG_FISCAL_YEAR;
/

CREATE OR REPLACE PACKAGE KF_PKG_INVOICE AS
    PROCEDURE VALIDATE_INVOICE (P_INVOICE_ID IN NUMBER);
    PROCEDURE UPDATE_STATUS (P_INVOICE_ID IN NUMBER, P_NEW_STATUS IN VARCHAR2);
    PROCEDURE SUBMIT_FOR_APPROVAL (P_INVOICE_ID IN NUMBER, P_REQUESTED_BY_USER_ID IN NUMBER);
END KF_PKG_INVOICE;
/

CREATE OR REPLACE PACKAGE KF_PKG_APPROVAL AS
    PROCEDURE VALIDATE_ENTITY (P_ENTITY_TYPE IN VARCHAR2, P_ENTITY_ID IN NUMBER);
    PROCEDURE SUBMIT_APPROVAL (
        P_ENTITY_TYPE IN VARCHAR2, 
        P_ENTITY_ID IN NUMBER, 
        P_REQUESTED_BY IN VARCHAR2,
        P_ASSIGNED_APPROVER IN VARCHAR2 DEFAULT NULL
    );
    PROCEDURE APPROVE (P_APPROVAL_ID IN NUMBER, P_DECISION_BY IN VARCHAR2, P_COMMENTS IN VARCHAR2 DEFAULT NULL);
    PROCEDURE REJECT (P_APPROVAL_ID IN NUMBER, P_DECISION_BY IN VARCHAR2, P_COMMENTS IN VARCHAR2);
END KF_PKG_APPROVAL;
/

CREATE OR REPLACE PACKAGE KF_PKG_PAYMENT AS
    PROCEDURE CREATE_PAYMENT (
        P_INVOICE_ID IN NUMBER,
        P_PAYMENT_AMOUNT IN NUMBER,
        P_PAYMENT_METHOD IN VARCHAR2,
        P_REFERENCE_NUMBER IN VARCHAR2,
        P_CREATED_BY_USER_ID IN NUMBER
    );
END KF_PKG_PAYMENT;
/

CREATE OR REPLACE PACKAGE KF_PKG_TDS AS
    FUNCTION CALCULATE_TDS (P_TAXABLE_AMOUNT IN NUMBER, P_TDS_RATE IN NUMBER) RETURN NUMBER;
    PROCEDURE CREATE_TDS_TRANSACTION (
        P_INVOICE_ID IN NUMBER,
        P_TDS_SECTION IN VARCHAR2,
        P_TDS_RATE IN NUMBER,
        P_CREATED_BY_USER_ID IN NUMBER
    );
END KF_PKG_TDS;
/

CREATE OR REPLACE PACKAGE KF_PKG_CASH_FLOW AS
    PROCEDURE VALIDATE_TRACKER (P_TRACKER_ID IN NUMBER);
    PROCEDURE SUBMIT_FOR_APPROVAL (P_TRACKER_ID IN NUMBER, P_REQUESTED_BY_USER_ID IN NUMBER);
END KF_PKG_CASH_FLOW;
/

-- ==========================================
-- 3. PACKAGE BODIES
-- ==========================================

CREATE OR REPLACE PACKAGE BODY KF_PKG_AUDIT AS
    PROCEDURE LOG_EVENT (
        P_USER_ID IN NUMBER,
        P_ACTION IN VARCHAR2,
        P_TABLE_NAME IN VARCHAR2,
        P_RECORD_ID IN VARCHAR2,
        P_OLD_VALUE IN CLOB DEFAULT NULL,
        P_NEW_VALUE IN CLOB DEFAULT NULL
    ) IS
        V_APEX_USER VARCHAR2(255);
        V_SESSION_ID VARCHAR2(255);
    BEGIN
        -- Safely get APEX context if it exists
        V_APEX_USER := SYS_CONTEXT('APEX$SESSION', 'APP_USER');
        
        BEGIN
            V_SESSION_ID := V('APP_SESSION');
        EXCEPTION WHEN OTHERS THEN
            V_SESSION_ID := NULL;
        END;

        INSERT INTO KF_AUDIT_LOG (
            USER_ID, APEX_SESSION_USER, ACTION, TABLE_NAME, RECORD_ID, 
            OLD_VALUE, NEW_VALUE, IP_ADDRESS, SESSION_ID
        ) VALUES (
            P_USER_ID, V_APEX_USER, P_ACTION, P_TABLE_NAME, P_RECORD_ID, 
            P_OLD_VALUE, P_NEW_VALUE, SYS_CONTEXT('USERENV', 'IP_ADDRESS'), V_SESSION_ID
        );
        -- Notice: No COMMIT here. The caller transaction controls the commit.
    END LOG_EVENT;
END KF_PKG_AUDIT;
/

CREATE OR REPLACE PACKAGE BODY KF_PKG_NOTIFICATION AS
    PROCEDURE CREATE_NOTIFICATION (
        P_USER_ID IN NUMBER,
        P_TITLE IN VARCHAR2,
        P_MESSAGE IN VARCHAR2,
        P_TYPE IN VARCHAR2 DEFAULT 'INFO',
        P_RELATED_ENTITY_TYPE IN VARCHAR2 DEFAULT NULL,
        P_RELATED_ENTITY_ID IN NUMBER DEFAULT NULL
    ) IS
    BEGIN
        INSERT INTO KF_NOTIFICATIONS (
            USER_ID, TYPE, TITLE, MESSAGE, REFERENCE_ENTITY, REFERENCE_ID
        ) VALUES (
            P_USER_ID, P_TYPE, P_TITLE, P_MESSAGE, P_RELATED_ENTITY_TYPE, P_RELATED_ENTITY_ID
        );
    END CREATE_NOTIFICATION;

    PROCEDURE MARK_AS_READ (P_NOTIFICATION_ID IN NUMBER) IS
    BEGIN
        UPDATE KF_NOTIFICATIONS 
        SET IS_READ = 'Y', READ_DATE = SYSTIMESTAMP 
        WHERE NOTIFICATION_ID = P_NOTIFICATION_ID;
    END MARK_AS_READ;

    PROCEDURE MARK_ALL_AS_READ (P_USER_ID IN NUMBER) IS
    BEGIN
        UPDATE KF_NOTIFICATIONS 
        SET IS_READ = 'Y', READ_DATE = SYSTIMESTAMP 
        WHERE USER_ID = P_USER_ID AND IS_READ = 'N';
    END MARK_ALL_AS_READ;
END KF_PKG_NOTIFICATION;
/

CREATE OR REPLACE PACKAGE BODY KF_PKG_FISCAL_YEAR AS
    FUNCTION GET_CURRENT_FISCAL_YEAR RETURN NUMBER IS
        v_id NUMBER;
    BEGIN
        -- Assuming FY runs Apr 1 to Mar 31
        SELECT FISCAL_YEAR_ID INTO v_id
        FROM KF_FISCAL_YEARS
        WHERE SYSDATE BETWEEN START_DATE AND END_DATE
        AND STATUS = 'ACTIVE';
        RETURN v_id;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN NULL;
    END GET_CURRENT_FISCAL_YEAR;

    FUNCTION IS_DATE_IN_FISCAL_YEAR (P_DATE IN DATE, P_FISCAL_YEAR_ID IN NUMBER) RETURN BOOLEAN IS
        v_start DATE;
        v_end DATE;
    BEGIN
        SELECT START_DATE, END_DATE INTO v_start, v_end 
        FROM KF_FISCAL_YEARS WHERE FISCAL_YEAR_ID = P_FISCAL_YEAR_ID;
        
        RETURN P_DATE BETWEEN v_start AND v_end;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN RETURN FALSE;
    END IS_DATE_IN_FISCAL_YEAR;
END KF_PKG_FISCAL_YEAR;
/

CREATE OR REPLACE PACKAGE BODY KF_PKG_INVOICE AS
    PROCEDURE VALIDATE_INVOICE (P_INVOICE_ID IN NUMBER) IS
        v_inv KF_INVOICES%ROWTYPE;
        v_vendor_status VARCHAR2(20);
        v_dup_count NUMBER;
    BEGIN
        SELECT * INTO v_inv FROM KF_INVOICES WHERE INVOICE_ID = P_INVOICE_ID;
        
        IF v_inv.INVOICE_DATE > v_inv.DUE_DATE THEN
            RAISE_APPLICATION_ERROR(-20001, 'Due date cannot be before invoice date.');
        END IF;

        IF v_inv.SUBTOTAL < 0 OR v_inv.TAX_AMOUNT < 0 OR v_inv.TDS_AMOUNT < 0 THEN
            RAISE_APPLICATION_ERROR(-20002, 'Monetary values cannot be negative.');
        END IF;
        
        IF v_inv.TOTAL_AMOUNT <= 0 THEN
            RAISE_APPLICATION_ERROR(-20003, 'Total amount must be greater than zero.');
        END IF;

        IF v_inv.TOTAL_AMOUNT != (v_inv.SUBTOTAL + v_inv.TAX_AMOUNT - v_inv.TDS_AMOUNT) THEN
            RAISE_APPLICATION_ERROR(-20004, 'Invoice total does not match Subtotal + Tax - TDS.');
        END IF;

        SELECT STATUS INTO v_vendor_status FROM KF_VENDORS WHERE VENDOR_ID = v_inv.VENDOR_ID;
        IF v_vendor_status != 'ACTIVE' THEN
            RAISE_APPLICATION_ERROR(-20005, 'Vendor is not active.');
        END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20006, 'Invoice or Vendor not found.');
    END VALIDATE_INVOICE;

    PROCEDURE UPDATE_STATUS (P_INVOICE_ID IN NUMBER, P_NEW_STATUS IN VARCHAR2) IS
    BEGIN
        IF P_NEW_STATUS NOT IN ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'CANCELLED') THEN
            RAISE_APPLICATION_ERROR(-20010, 'Invalid invoice status: ' || P_NEW_STATUS);
        END IF;
        UPDATE KF_INVOICES SET STATUS = P_NEW_STATUS, UPDATED_DATE = SYSTIMESTAMP WHERE INVOICE_ID = P_INVOICE_ID;
    END UPDATE_STATUS;

    PROCEDURE SUBMIT_FOR_APPROVAL (P_INVOICE_ID IN NUMBER, P_REQUESTED_BY_USER_ID IN NUMBER) IS
        v_status VARCHAR2(50);
        v_username VARCHAR2(100);
    BEGIN
        SELECT STATUS INTO v_status FROM KF_INVOICES WHERE INVOICE_ID = P_INVOICE_ID FOR UPDATE;
        
        IF v_status != 'DRAFT' AND v_status != 'REJECTED' THEN
            RAISE_APPLICATION_ERROR(-20011, 'Only DRAFT or REJECTED invoices can be submitted.');
        END IF;

        VALIDATE_INVOICE(P_INVOICE_ID);
        
        SELECT USERNAME INTO v_username FROM KF_USERS WHERE USER_ID = P_REQUESTED_BY_USER_ID;

        UPDATE_STATUS(P_INVOICE_ID, 'PENDING_APPROVAL');
        
        KF_PKG_APPROVAL.SUBMIT_APPROVAL(
            P_ENTITY_TYPE => 'INVOICE',
            P_ENTITY_ID => P_INVOICE_ID,
            P_REQUESTED_BY => v_username
        );
        
        KF_PKG_AUDIT.LOG_EVENT(P_REQUESTED_BY_USER_ID, 'UPDATE', 'KF_INVOICES', TO_CHAR(P_INVOICE_ID));
    END SUBMIT_FOR_APPROVAL;
END KF_PKG_INVOICE;
/

CREATE OR REPLACE PACKAGE BODY KF_PKG_APPROVAL AS
    PROCEDURE VALIDATE_ENTITY (P_ENTITY_TYPE IN VARCHAR2, P_ENTITY_ID IN NUMBER) IS
        v_count NUMBER;
    BEGIN
        IF P_ENTITY_TYPE = 'INVOICE' THEN
            SELECT COUNT(*) INTO v_count FROM KF_INVOICES WHERE INVOICE_ID = P_ENTITY_ID;
        ELSIF P_ENTITY_TYPE = 'CASH_FLOW' THEN
            SELECT COUNT(*) INTO v_count FROM KF_CASH_FLOW_TRACKERS WHERE TRACKER_ID = P_ENTITY_ID;
        ELSE
            RAISE_APPLICATION_ERROR(-20020, 'Invalid entity type for approval.');
        END IF;
        
        IF v_count = 0 THEN
            RAISE_APPLICATION_ERROR(-20021, 'Entity ID does not exist for the given Entity Type.');
        END IF;
    END VALIDATE_ENTITY;

    PROCEDURE SUBMIT_APPROVAL (
        P_ENTITY_TYPE IN VARCHAR2, 
        P_ENTITY_ID IN NUMBER, 
        P_REQUESTED_BY IN VARCHAR2,
        P_ASSIGNED_APPROVER IN VARCHAR2 DEFAULT NULL
    ) IS
    BEGIN
        VALIDATE_ENTITY(P_ENTITY_TYPE, P_ENTITY_ID);
        INSERT INTO KF_APPROVAL_REQUESTS (ENTITY_TYPE, ENTITY_ID, REQUESTED_BY, ASSIGNED_APPROVER)
        VALUES (P_ENTITY_TYPE, P_ENTITY_ID, P_REQUESTED_BY, P_ASSIGNED_APPROVER);
    END SUBMIT_APPROVAL;

    PROCEDURE APPROVE (P_APPROVAL_ID IN NUMBER, P_DECISION_BY IN VARCHAR2, P_COMMENTS IN VARCHAR2 DEFAULT NULL) IS
        v_req KF_APPROVAL_REQUESTS%ROWTYPE;
    BEGIN
        SELECT * INTO v_req FROM KF_APPROVAL_REQUESTS WHERE APPROVAL_ID = P_APPROVAL_ID FOR UPDATE;
        
        IF v_req.STATUS != 'PENDING' THEN
            RAISE_APPLICATION_ERROR(-20022, 'Only pending requests can be approved.');
        END IF;

        UPDATE KF_APPROVAL_REQUESTS SET STATUS = 'APPROVED', DECISION_DATE = SYSTIMESTAMP WHERE APPROVAL_ID = P_APPROVAL_ID;
        
        INSERT INTO KF_APPROVAL_HISTORY (APPROVAL_ID, DECISION_BY, DECISION, COMMENTS)
        VALUES (P_APPROVAL_ID, P_DECISION_BY, 'APPROVED', P_COMMENTS);
        
        IF v_req.ENTITY_TYPE = 'INVOICE' THEN
            KF_PKG_INVOICE.UPDATE_STATUS(v_req.ENTITY_ID, 'APPROVED');
        ELSIF v_req.ENTITY_TYPE = 'CASH_FLOW' THEN
            UPDATE KF_CASH_FLOW_TRACKERS SET STATUS = 'APPROVED', APPROVED_BY = P_DECISION_BY, APPROVED_DATE = SYSTIMESTAMP WHERE TRACKER_ID = v_req.ENTITY_ID;
        END IF;
    END APPROVE;

    PROCEDURE REJECT (P_APPROVAL_ID IN NUMBER, P_DECISION_BY IN VARCHAR2, P_COMMENTS IN VARCHAR2) IS
        v_req KF_APPROVAL_REQUESTS%ROWTYPE;
    BEGIN
        IF P_COMMENTS IS NULL THEN
            RAISE_APPLICATION_ERROR(-20023, 'Rejection reason is required.');
        END IF;
        
        SELECT * INTO v_req FROM KF_APPROVAL_REQUESTS WHERE APPROVAL_ID = P_APPROVAL_ID FOR UPDATE;
        
        IF v_req.STATUS != 'PENDING' THEN
            RAISE_APPLICATION_ERROR(-20024, 'Only pending requests can be rejected.');
        END IF;

        UPDATE KF_APPROVAL_REQUESTS SET STATUS = 'REJECTED', DECISION_DATE = SYSTIMESTAMP, COMMENTS = P_COMMENTS WHERE APPROVAL_ID = P_APPROVAL_ID;
        
        INSERT INTO KF_APPROVAL_HISTORY (APPROVAL_ID, DECISION_BY, DECISION, COMMENTS)
        VALUES (P_APPROVAL_ID, P_DECISION_BY, 'REJECTED', P_COMMENTS);
        
        IF v_req.ENTITY_TYPE = 'INVOICE' THEN
            KF_PKG_INVOICE.UPDATE_STATUS(v_req.ENTITY_ID, 'REJECTED');
        ELSIF v_req.ENTITY_TYPE = 'CASH_FLOW' THEN
            UPDATE KF_CASH_FLOW_TRACKERS SET STATUS = 'REJECTED' WHERE TRACKER_ID = v_req.ENTITY_ID;
        END IF;
    END REJECT;
END KF_PKG_APPROVAL;
/

CREATE OR REPLACE PACKAGE BODY KF_PKG_PAYMENT AS
    PROCEDURE CREATE_PAYMENT (
        P_INVOICE_ID IN NUMBER,
        P_PAYMENT_AMOUNT IN NUMBER,
        P_PAYMENT_METHOD IN VARCHAR2,
        P_REFERENCE_NUMBER IN VARCHAR2,
        P_CREATED_BY_USER_ID IN NUMBER
    ) IS
        v_inv KF_INVOICES%ROWTYPE;
        v_paid NUMBER := 0;
        v_outstanding NUMBER := 0;
    BEGIN
        IF P_PAYMENT_AMOUNT <= 0 THEN
            RAISE_APPLICATION_ERROR(-20030, 'Payment amount must be greater than zero.');
        END IF;

        SELECT * INTO v_inv FROM KF_INVOICES WHERE INVOICE_ID = P_INVOICE_ID FOR UPDATE;
        
        IF v_inv.STATUS NOT IN ('APPROVED', 'PARTIALLY_PAID') THEN
            RAISE_APPLICATION_ERROR(-20031, 'Payments can only be applied to APPROVED or PARTIALLY_PAID invoices.');
        END IF;

        SELECT NVL(SUM(PAYMENT_AMOUNT), 0) INTO v_paid FROM KF_PAYMENTS WHERE INVOICE_ID = P_INVOICE_ID AND STATUS = 'COMPLETED';
        v_outstanding := v_inv.TOTAL_AMOUNT - v_paid;
        
        IF P_PAYMENT_AMOUNT > v_outstanding THEN
            RAISE_APPLICATION_ERROR(-20032, 'Payment amount exceeds outstanding balance.');
        END IF;

        INSERT INTO KF_PAYMENTS (INVOICE_ID, VENDOR_ID, PAYMENT_DATE, PAYMENT_AMOUNT, PAYMENT_METHOD, REFERENCE_NUMBER, STATUS)
        VALUES (P_INVOICE_ID, v_inv.VENDOR_ID, SYSDATE, P_PAYMENT_AMOUNT, P_PAYMENT_METHOD, P_REFERENCE_NUMBER, 'COMPLETED');

        -- Update status
        IF (v_paid + P_PAYMENT_AMOUNT) >= v_inv.TOTAL_AMOUNT THEN
            KF_PKG_INVOICE.UPDATE_STATUS(P_INVOICE_ID, 'PAID');
        ELSE
            KF_PKG_INVOICE.UPDATE_STATUS(P_INVOICE_ID, 'PARTIALLY_PAID');
        END IF;

        KF_PKG_AUDIT.LOG_EVENT(P_CREATED_BY_USER_ID, 'INSERT', 'KF_PAYMENTS', TO_CHAR(P_INVOICE_ID));
    END CREATE_PAYMENT;
END KF_PKG_PAYMENT;
/

CREATE OR REPLACE PACKAGE BODY KF_PKG_TDS AS
    FUNCTION CALCULATE_TDS (P_TAXABLE_AMOUNT IN NUMBER, P_TDS_RATE IN NUMBER) RETURN NUMBER IS
    BEGIN
        IF P_TDS_RATE < 0 OR P_TDS_RATE > 100 THEN
            RAISE_APPLICATION_ERROR(-20040, 'TDS Rate must be between 0 and 100.');
        END IF;
        RETURN (P_TAXABLE_AMOUNT * P_TDS_RATE) / 100;
    END CALCULATE_TDS;

    PROCEDURE CREATE_TDS_TRANSACTION (
        P_INVOICE_ID IN NUMBER,
        P_TDS_SECTION IN VARCHAR2,
        P_TDS_RATE IN NUMBER,
        P_CREATED_BY_USER_ID IN NUMBER
    ) IS
        v_inv KF_INVOICES%ROWTYPE;
        v_taxable NUMBER;
        v_tds NUMBER;
    BEGIN
        SELECT * INTO v_inv FROM KF_INVOICES WHERE INVOICE_ID = P_INVOICE_ID;
        v_taxable := v_inv.SUBTOTAL; -- Simplified assumption for taxable base
        v_tds := CALCULATE_TDS(v_taxable, P_TDS_RATE);
        
        INSERT INTO KF_TDS_TRANSACTIONS (INVOICE_ID, VENDOR_ID, TDS_SECTION, TDS_RATE, TAXABLE_AMOUNT, TDS_AMOUNT, DEDUCTION_DATE, STATUS)
        VALUES (P_INVOICE_ID, v_inv.VENDOR_ID, P_TDS_SECTION, P_TDS_RATE, v_taxable, v_tds, SYSDATE, 'PENDING');
        
        KF_PKG_AUDIT.LOG_EVENT(P_CREATED_BY_USER_ID, 'INSERT', 'KF_TDS_TRANSACTIONS', TO_CHAR(P_INVOICE_ID));
    END CREATE_TDS_TRANSACTION;
END KF_PKG_TDS;
/

CREATE OR REPLACE PACKAGE BODY KF_PKG_CASH_FLOW AS
    PROCEDURE VALIDATE_TRACKER (P_TRACKER_ID IN NUMBER) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM KF_CASH_FLOW_ENTRIES WHERE TRACKER_ID = P_TRACKER_ID;
        IF v_count = 0 THEN
            RAISE_APPLICATION_ERROR(-20050, 'Tracker has no entries.');
        END IF;
    END VALIDATE_TRACKER;

    PROCEDURE SUBMIT_FOR_APPROVAL (P_TRACKER_ID IN NUMBER, P_REQUESTED_BY_USER_ID IN NUMBER) IS
        v_username VARCHAR2(100);
        v_status VARCHAR2(50);
    BEGIN
        SELECT STATUS INTO v_status FROM KF_CASH_FLOW_TRACKERS WHERE TRACKER_ID = P_TRACKER_ID FOR UPDATE;
        IF v_status != 'DRAFT' THEN
            RAISE_APPLICATION_ERROR(-20051, 'Only DRAFT trackers can be submitted.');
        END IF;
        
        VALIDATE_TRACKER(P_TRACKER_ID);
        SELECT USERNAME INTO v_username FROM KF_USERS WHERE USER_ID = P_REQUESTED_BY_USER_ID;
        
        UPDATE KF_CASH_FLOW_TRACKERS SET STATUS = 'PENDING_APPROVAL' WHERE TRACKER_ID = P_TRACKER_ID;
        
        KF_PKG_APPROVAL.SUBMIT_APPROVAL(
            P_ENTITY_TYPE => 'CASH_FLOW',
            P_ENTITY_ID => P_TRACKER_ID,
            P_REQUESTED_BY => v_username
        );
        KF_PKG_AUDIT.LOG_EVENT(P_REQUESTED_BY_USER_ID, 'UPDATE', 'KF_CASH_FLOW_TRACKERS', TO_CHAR(P_TRACKER_ID));
    END SUBMIT_FOR_APPROVAL;
END KF_PKG_CASH_FLOW;
/
